import { Metadata } from 'next'
import { Urbanist } from 'next/font/google'

const urbanist = Urbanist({
  variable: '--font-urbanist',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Frog CRM - Login',
  description: 'Generated by create next app',
}

export default function RegisterLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="pt-BR">
      <body className={`${urbanist.variable}`}>{children}</body>
    </html>
  )
}
